### ISSUE TITLE
Curriculum 

### ISSUE THREAD

**Issue by dominosfordays** [dominosfordays/utilities#1]
### Q4 2019 (October-December)
- [x] [Deep Learning for Coders 2018](https://www.youtube.com/playlist?list=PLfYUBJiXbdtS2UQRzyrxmyVHoGW0gmLSM) See Issue #2 
- [ ] [SQL for Data Science](https://www.coursera.org/learn/sql-for-data-science) See Issue #12
- [x] [Convolutional Neural Networks for Visual Recognition - Module 2](http://cs231n.github.io/) See Issue #13 

### Q1 2020 (January-March)
- [ ] [Machine Learning for Coders ](http://course18.fast.ai/ml) See Issue #6 
- [ ] [Treehouse Python Track](https://teamtreehouse.com/tracks/learn-python) See Issue #10 
- [ ] [Convolutional Neural Networks for Visual Recognition - Module 0-1](http://cs231n.github.io/) See Issue #13
- [ ] [Learning How To Learn](https://www.coursera.org/learn/learning-how-to-learn/home/welcome)

### Q2 2020 (April-June)
- [ ] [Computational Linear Algebra](https://github.com/fastai/numerical-linear-algebra/blob/master/README.md) See Issue #7 
- [ ] [Harvard Intro to Computer Science](https://www.edx.org/course/cs50s-introduction-to-computer-science) See Issue #8 

### Q3 2020 (July-September)
- [ ] [Designing, Running, and Analyzing Experiments](https://www.coursera.org/learn/designexperiments/home/welcome) See Issue #9 
- [ ] [Deep Learning for Coders 2019](https://course.fast.ai/) See Issue #3 

### Q4 2020 (October-December)
- [ ] [State of the Art Deep Learning for Coders 2018](https://www.youtube.com/playlist?list=PLfYUBJiXbdtTttBGq-u2zeY1OTjs5e-Ia) See Issue #4 
- [ ] [Deep Learning from the Foundations](https://course.fast.ai/part2) See Issue #5

## Additional References and Courses
- [ ] [Andrew Ng Machine Learning](https://www.coursera.org/learn/machine-learning) See Issue #11 
- [Example Curriculum](https://towardsdatascience.com/my-self-created-ai-masters-degree-ddc7aae92d0e)

**Comment by dominosfordays** [comment]
(Intro to Containers)[https://www.aws.training/Details/eLearning?id=27182]
(EC2 Service for Kubernetes)[https://www.aws.training/Details/eLearning?id=32894]

**Comment by dominosfordays** [comment]
https://towardsdatascience.com/my-self-created-ai-masters-degree-ddc7aae92d0e

**Comment by dominosfordays** [comment]
This isn't turning out to be the best way for me to motivate myself to learn and stay accountable... needed to reconsider. Turning to 30 day setup for a trial run.
